apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-app
  namespace: monitoring
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc 
  project: monitoring 
  source: 
    path: GitOps/monitoring/Grafana/overlays/ESL
    repoURL: https://github.com/xela-engineer/k8s-gitops-practice
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
